#!/bin/sh

set -e

set -x
autoreconf --version
autoconf --version
automake --version
libtool --version
pkg-config --version

if test -f Makefile; then
  make distclean
fi
rm -rf *~ *.cache *.m4 config.guess config.log \
	config.status config.sub depcomp ltmain.sh
autoreconf --verbose --install --force
